name: Python brute-force 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bruteforce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install (no deps)
        run: python -m pip install --upgrade pip

      - name: Run bruteforce example
        run: |
          python bruteforce.py -p abc -A lower -m 3
